### ISSUE TITLE
No documentation on migrating from multi-tenant-core

### ISSUE THREAD

**Issue by dbourget** [multi-tenant/grails-multi-tenant-single-db#15]
Since multi-tenant-core is not supported in Grails 2.x, it would be useful to know how to migrate to this plugin.

**Comment by jdschmitt** [comment]
I'd appreciate this as well. We are currently using multi-tenant-core in a single DB environment. We are considering moving to multi DB since MTC doesn't support Grails 2.0 and there appears to be no work on it. We may stick with single DB and migrate to this plugin but would like to know if there are any known considerations when doing so.

**Comment by kimble** [comment]
I don't think anyone is going to write this kinda documentation without getting payed for it.

**Comment by dbourget** [comment]
@kimble I was under the impression that this was an open source project interested in collaboration with other parties. Can you clarify the nature of the project? Maybe remove it from the Grails plugin repository if this is an in-house or commercial project not really interested in use outside a designated or paying group.

**Comment by kimble** [comment]
Well. it's on Github, published under Apache 2.0 licence and quite a few companies use it. Feel free to contribute.
